//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.CompanyCommunicator.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.CompanyCommunicator.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact your IT admin for permission to view this data..
        /// </summary>
        public static string AdminConsentError {
            get {
                return ResourceManager.GetString("AdminConsentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App Not Installed.
        /// </summary>
        public static string AppNotInstalled {
            get {
                return ResourceManager.GetString("AppNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery Status.
        /// </summary>
        public static string ColumnName_DeliveryStatus {
            get {
                return ResourceManager.GetString("ColumnName_DeliveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exported By.
        /// </summary>
        public static string ColumnName_ExportedBy {
            get {
                return ResourceManager.GetString("ColumnName_ExportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export TimeStamp.
        /// </summary>
        public static string ColumnName_ExportTimeStamp {
            get {
                return ResourceManager.GetString("ColumnName_ExportTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message Title.
        /// </summary>
        public static string ColumnName_MessageTitle {
            get {
                return ResourceManager.GetString("ColumnName_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sent TimeStamp.
        /// </summary>
        public static string ColumnName_SentTimeStamp {
            get {
                return ResourceManager.GetString("ColumnName_SentTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status Reason.
        /// </summary>
        public static string ColumnName_StatusReason {
            get {
                return ResourceManager.GetString("ColumnName_StatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team ID.
        /// </summary>
        public static string ColumnName_TeamId {
            get {
                return ResourceManager.GetString("ColumnName_TeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team Name.
        /// </summary>
        public static string ColumnName_TeamName {
            get {
                return ResourceManager.GetString("ColumnName_TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPN.
        /// </summary>
        public static string ColumnName_Upn {
            get {
                return ResourceManager.GetString("ColumnName_Upn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User ID.
        /// </summary>
        public static string ColumnName_UserId {
            get {
                return ResourceManager.GetString("ColumnName_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string ColumnName_UserName {
            get {
                return ResourceManager.GetString("ColumnName_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} (copy).
        /// </summary>
        public static string DuplicateText {
            get {
                return ResourceManager.GetString("DuplicateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Something went wrong. Try exporting the results again..
        /// </summary>
        public static string ExportFailureText {
            get {
                return ResourceManager.GetString("ExportFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create conversation. Error message: {0}.
        /// </summary>
        public static string FailedToCreateConversationFormat {
            get {
                return ResourceManager.GetString("FailedToCreateConversationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create conversation with teams user: {0}. Exception: {1}.
        /// </summary>
        public static string FailedToCreateConversationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToCreateConversationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create conversation. Request throttled. Error message: {0}&quot;.
        /// </summary>
        public static string FailedToCreateConversationThrottledFormt {
            get {
                return ResourceManager.GetString("FailedToCreateConversationThrottledFormt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to find the team {0} in DB..
        /// </summary>
        public static string FailedToFindTeamInDbFormat {
            get {
                return ResourceManager.GetString("FailedToFindTeamInDbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to find the User application: {0} in the organization&apos;s app catalog..
        /// </summary>
        public static string FailedToFindUserAppInAppCatalog {
            get {
                return ResourceManager.GetString("FailedToFindUserAppInAppCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to sync all users. Status Code: {0} Exception: {1}.
        /// </summary>
        public static string FailedToGetAllUsersFormat {
            get {
                return ResourceManager.GetString("FailedToGetAllUsersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to get conversation id for user: {0}. Status Code: {1} Exception: {2}.
        /// </summary>
        public static string FailedToGetConversationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToGetConversationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to get members for group {0}: {1}.
        /// </summary>
        public static string FailedToGetMembersForGroupFormat {
            get {
                return ResourceManager.GetString("FailedToGetMembersForGroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to get members for list of users: {0}.
        /// </summary>
        public static string FailedToGetMembersForListFormat {
            get {
                return ResourceManager.GetString("FailedToGetMembersForListFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to get members for team {0}: {1}.
        /// </summary>
        public static string FailedToGetMembersForTeamFormat {
            get {
                return ResourceManager.GetString("FailedToGetMembersForTeamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to install application for user: {0}. Exception: {1}.
        /// </summary>
        public static string FailedToInstallApplicationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToInstallApplicationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to prepare the message for sending:{0}.
        /// </summary>
        public static string FailtoPrepareMessageFormat {
            get {
                return ResourceManager.GetString("FailtoPrepareMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This file contains the results you exported..
        /// </summary>
        public static string FileCardDescription {
            get {
                return ResourceManager.GetString("FileCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The link for this download has expired. Export the results again..
        /// </summary>
        public static string FileCardExpireText {
            get {
                return ResourceManager.GetString("FileCardExpireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ExportData.
        /// </summary>
        public static string FileName_ExportData {
            get {
                return ResourceManager.GetString("FileName_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message_Delivery.
        /// </summary>
        public static string FileName_Message_Delivery {
            get {
                return ResourceManager.GetString("FileName_Message_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metadata.
        /// </summary>
        public static string FileName_Metadata {
            get {
                return ResourceManager.GetString("FileName_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your file is ready to download. A copy is also available in OneDrive..
        /// </summary>
        public static string FileReadyText {
            get {
                return ResourceManager.GetString("FileReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Something went wrong. Try exporting the results again..
        /// </summary>
        public static string FileUploadErrorText {
            get {
                return ResourceManager.GetString("FileUploadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The notification has {0} groups as its recipients. It shouldn&apos;t exceed {1} groups..
        /// </summary>
        public static string NumberOfGroupsExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfGroupsExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The notification has {0} rosters as its recipients. It shouldn&apos;t exceed {1} rosters..
        /// </summary>
        public static string NumberOfRostersExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfRostersExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The notification has {0} teams as its recipients. It shouldn&apos;t exceed {1} teams..
        /// </summary>
        public static string NumberOfTeamsExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfTeamsExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permission declined. We will not proceed with the export..
        /// </summary>
        public static string PermissionDeclinedText {
            get {
                return ResourceManager.GetString("PermissionDeclinedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recipient Not Found.
        /// </summary>
        public static string RecipientNotFound {
            get {
                return ResourceManager.GetString("RecipientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Succeeded.
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Throttled.
        /// </summary>
        public static string Throttled {
            get {
                return ResourceManager.GetString("Throttled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User application not found. Make sure the User app is uploaded to your organization&apos;s app catalog..
        /// </summary>
        public static string UserAppNotFound {
            get {
                return ResourceManager.GetString("UserAppNotFound", resourceCulture);
            }
        }
    }
}
